name: Build and Deploy
on:
  push:
    paths: [ "project/zy-lib/src/**/*.*"] # Trigger the action only when files change in the folders defined here
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false
      - name: Install and Build Library ğŸ”§
        run: | # Install npm packages, increase version PATCH and build the library files
          npm install
          cd projects/zy-lib/
          npm version patch
          cd ../../
          npm run build:lib
      - name: Deploy ğŸš€
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: release # The branch the action should deploy to.
          FOLDER: dist/zy-lib # The folder that the build-storybook script generates files.
          CLEAN: true # Automatically remove deleted files from the deploy branch
          TARGET_FOLDER: zy-lib # The folder that we serve our Storybook files from
